name: Sync Changes from AWS

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Sync changes from AWS
      run: |
        git fetch origin
        git pull origin main
        git add .
        git commit -m "Sync changes from AWS"
        git push origin main
